# Generated by Django 5.0.6 on 2024-05-28 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCurriculum',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Название дисциплины')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Номер семестра')),
            ],
            options={
                'verbose_name': 'Дисциплина учебного плана',
                'verbose_name_plural': 'Дисциплины учебного плана',
            },
        ),
        migrations.CreateModel(
            name='UniversityTeacher',
            fields=[
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
                ('university_abbreviation', models.CharField(max_length=10, verbose_name='Аббревиатура университета')),
                ('faculty', models.CharField(max_length=20, verbose_name='Факультета университета')),
                ('department', models.CharField(max_length=20, verbose_name='Кафедра университета')),
                ('academic_title', models.CharField(max_length=100, verbose_name='Ученое звание')),
                ('phone_number', models.CharField(help_text='+7 (***) ***-**-**', max_length=20, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(upload_to='img/teachers', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Преподаватель университета',
                'verbose_name_plural': 'Преподаватели университета',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_last_changed', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='Заголовок учебного плана')),
                ('year_of_start', models.PositiveSmallIntegerField(verbose_name='Год набора')),
                ('year_of_end', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('academic_level', models.CharField(max_length=50, verbose_name='Академический уровень')),
                ('years_to_study', models.CharField(max_length=50, verbose_name='Срок обучения')),
                ('university_abbreviation', models.CharField(max_length=10, verbose_name='Аббревиатура университета')),
                ('faculty', models.CharField(max_length=20, verbose_name='Факультета университета')),
                ('department', models.CharField(max_length=20, verbose_name='Кафедра университета')),
                ('branch_of_knowledge', models.CharField(max_length=100, verbose_name='Отрасль знаний')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
                ('education_program', models.CharField(max_length=100, verbose_name='Образовательная программа')),
                ('speciality_addition_info', models.CharField(blank=True, max_length=150, verbose_name='Дополнительная информация')),
                ('form_education', models.CharField(choices=[('Очная', 'Очная'), ('Заочная', 'Заочная')], max_length=10, verbose_name='Форма обучения')),
                ('citizenship', models.CharField(choices=[('Россия', 'Россия'), ('Иностранец', 'Иностранец')], max_length=10, verbose_name='Гражданство')),
                ('language_institution', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский')], max_length=50, verbose_name='Язык обучения')),
                ('enrollment_number', models.PositiveSmallIntegerField(verbose_name='Номер набора')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subjects', to='app_curriculum_ms.subjectcurriculum', verbose_name='Дисциплины')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_curriculum_ms.universityteacher', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
    ]
